### ISSUE TITLE
List Enhancement functions

### ISSUE THREAD

**Issue by arnecoomans** [arnecoomans/camping.cmns.nl#8]
- [x] (re)trigger calculate distance from list view
- [x] Display as: travel plan or blog post
- [x] Add media to list, in order -- waiting for #4
- [x] Better distinction in distances between locations and activities
- [x] Edit function in list items -- #48 
- [x] Up/Down in ordering -- see #7 
- [x] use list templates - combine template for overview and per list item

**Comment by arnecoomans** [comment]
Calculations: use https://icons.getbootstrap.com/icons/calculator/
